### PR TITLE
Cone mosaic o sintegration time

### PR DESCRIPTION
**Pull request by DavidBrainard**
See attached PDF.

[ConeMosaicEnhancements.pdf](https://github.com/isetbio/isetbio/files/521770/ConeMosaicEnhancements.pdf)

### CODE REVIEW

**Comment by jamesgolden1** [comment]
A minor issue, I got the following error running with Matlab 2015a:

```
Error using colorbar (line 55)
A Colorbar can not be a child of an object of type uitab.

Error in v_osTimeStep>plotEverything (line 297)
    hC = colorbar('Location', 'NorthOutside', 'parent', timeSeriesTab);
```

Once I commented lines 297-299, the code ran through. This looks great - the visualizations are very nice.

Assuming that colorbar problem is a version error, I am all for merging this into master.

**Comment by wandell** [comment]
I am running through the validation script and making notes. I write this just so you know not to give up on me.

* The script runs and figures look great.
* Trivial thing:  I suggest adding something like this code on line 464, or thereabouts.

    theOIsequence = cell(1,numel(oiTimeAxis));

* I love the tiny cone mosaic you generate.  We should definitely put that into the main distribution.
* I am thinking about the rounding with respect to eye movements and cone integration time.  Maybe we should always be forcing this and simply tell the user?  I can't see yet whether we are announcing the little rounding issues or not;  ** THIS IS THE ONLY ISSUE THAT WOULD GIVE ME PAUSE BEFORE MERGING SO FAR**
* I need more time to study.  Am headed to watch the debate, sigh.

**Comment by npcottaris** [comment]
Hi Brian,

Thanks for the comments.
1) I have added the cell array init for `theOIsequence` as you suggested.

2) With respect to the eye movement/cone integration rounding issue:
At the end of the `coneMosaicGenerate()` function of `v_osTimeStep`, we compute a long sequence of eye movements for the entire OIsequence:
```
stimulusSamplingInterval = oiTimeAxis(2)-oiTimeAxis(1);
eyeMovementsNumPerOpticalImage = stimulusSamplingInterval/theConeMosaic.integrationTime;
eyeMovementsNum = round(eyeMovementsNumPerOpticalImage*opticalImageSequenceLength);
theConeMosaic.emGenSequence(eyeMovementsNum);
```
Subsequently, the`computeForOISequence`method of `@coneMosaic` applies different parts of this sequence to different optical images, to compute the isomerizations for each optical image as follows:
```
for oiIndex = 1:numel(oiSequence)
  % Retrieve eye movements for current OI
  if (oiIndex < numel(oiSequence))
       eyeMovementIndices = find((eyeMovementTimeAxis >= oiTimeAxis(oiIndex)) & (eyeMovementTimeAxis < oiTimeAxis(oiIndex+1)));
  else
       eyeMovementIndices = find(eyeMovementTimeAxis >= oiTimeAxis(oiIndex));
  end

  % Compute absorptions for current OI and eye movement path
   absorptionsForThisOI = obj.compute(oiSequence{oiIndex}, ...
            'emPath', eyeMovementsForOISequence(eyeMovementIndices,:), ...       
            'newNoise', newNoise, ...
            'currentFlag', false ...   
            );
        
   % Concatenate absorption sequences
   absorptions = cat(3, absorptions, absorptionsForThisOI);
end 
```

In this scheme, if `eyeMovementsNumPerOpticalImage` is not an integer, say 3.3, some OIs will be sampled with 3 eye movements, whereas others with 4. In such cases, and for eye movements whose `time stamp + integrationTime` exceeds the duration of the current OI, we should probably compute absorptions using a weighted average of the photons in the current OI and the photons in the subsequent OI, but we currently do not do that. I can change the code to implement this, or we can decide that `computeForOISequence` will throw an error if `eyeMovementsNumPerOpticalImage` is non-integer. I am voting for the former solution (weighted average).

Nicolas

**Comment by wandell** [comment]
* If you have a means of handling the fractional eye movement case, that's fine.  I don't have a problem with the forced quantization, either.  Perhaps you should make the choice based on whether the code will be more robust and easier to read one way or the other.  

*  I am now reading through the PDF and the bit about computeForOISequence().  This is very valuable and important.  In the PDF the text says cMosaic.compute(... where I think cMOsaic.computeForOISequence() is meant; but I am not completely sure.  

* I wonder if we could write the code using only cMosaic.compute() and in the case when the OI is a cell array, you switch into the computeForOISequence() methods?  I vaguely remember doing this for sensorCompute in the past, and it simplifies the call, though it means the code is less explicit about whether we are acting on an OI cell array or a single one.

**Comment by wandell** [comment]
A few more thoughts

* Let's replace the function `uniformFieldSceneCreate` with `sceneCreate('uniform equal photon')`, which is a stanford function.

* I really like the general function `oiSequenceGenerateForRampedSceneModulation`, which James and I never wrote but discussed.  Perhaps we could expose that as a utility along the lines of

     oiSequence = oiComputeModulate(oi,scene,timeScale);

*  Or, perhaps we should just add the functionality to oiCompute() as in

    oiSequence = oiCompute(oi,scene,'cRamp',cRampVector);
 
The function would reduce to the usual compute without the cRamp parameter/value.

* `computeForOISequence` looks pretty good, though I could use a few more comments as you reason about the eye movement position.  Probably I should write the comments and check with you after the code is committed.

I am ready to merge, when you are.  LGTM, as they say.

**Comment by wandell** [comment]
@hjiang36 and I were reading the code and preparing to use this branch for our Vernier paper.  One main thought, which we think could matter.

1. At present, you compute an entire oiSequence in the v_osTimeStep2.m code.  There are something like 15 time steps and 15 oi's.  

We think that it might be best to create a new class, say oiSequence.  That object would have parameters

    oiSequence.
        oiFixed
       oiVarying
      timeScale

The ith member of the sequence would be computed by

       oiFixed + timeScale(i)*oiVarying

The function 

     coneMosaic.compute(input)  

would check for the type of input.  If it is a oiSequence, it would build the oiSequence on the fly during the computation.  This saves the oiSequence{} size, which in the current code keeps adding the irradiance data with each step in the loop.  The oiSequence structure could have as many scalars over time as we like without increasing the size of the data representation.

2.  Separately - handling the multiple time bases is important, and great that you are handling it.  The code as it stands has all of these as different variables that are clear named.  But the readability of the sections of the code where you are finding the appropriate time base is hard for me.  These are the long find() statements ...

     find(many time bases) 

Maybe we should draft functions for performing the operations when we are coordinating the time bases.  In a way, this is like your coneMosaic.resample() code.

3. Finally, the name resample might be changed to reflect that it is temporal resample (e.g., tResample) rather than spatial resample?

**Comment by wandell** [comment]
Clearly, we couldn't figure out how to make the numbered list work in the previous comment.  Oh well.

**Comment by npcottaris** [comment]
Brian,

* I have simplified the logic for handling multiple time bases. It now resides in `computeForOISequence()`. This function now handles any combination of `integrationTime` and `inter-oi interval`, doing partial photon integrations as needed. Yeah ! Proof of correctness can be obtained by running `v_osTimeStep` which computes isomerizations for 3 different inter-oi intervals, but identical integrationTimes, and which shows that the estimated absorptions do not depend on the inter-oi interval.

* I have created the `oiSequence` class for handling sequences of optical images with on-the-fly  computation of the OI using the scheme that you suggested, with some enhancements of my own. Please see/run `t_oiSequence` for example usage.

* The `coneMosaic.resample` method has been renamed to `t_Resample`.

* In `v_osTimeStep`, the function `uniformFieldSceneCreate` uses `sceneCreate('uniform equal photon')` .

Regarding having a `single coneMosaic.compute()` method.
* This can be done by renaming the current `compute()` method as a private function `computeForSingleOI` , making the `computeForOISequence` also private, and by writing a public (gateway) method named `compute`, which will choose with of the two private methods is to be called based on the OI type (sequence or single oi). 
* Do we still need the 'append' functionality of the existing `compute` method, now that we have `oiSequence` functionality?

**Comment by npcottaris** [comment]
Brian, Just a brief comment.
The readability and code structure  of functions with postfix 2 is not great, I agree. These were not meant for your eyes. They are intermediate, work in progress versions. I guess I should have made that explicit in the commit comment.

Thanks for the suggestions. I will be getting back to you in the next couple of days.

Best,
Nicolas


On Oct 22, 2016, at 6:33 PM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:

Separately - handling the multiple time bases is important, and great that you are handling it. The code as it stands has all of these as different variables that are clear named. But the readability of the sections of the code where you are finding the appropriate time base is hard for me. These are the long find() statements ...

**Comment by wandell** [comment]
Great stuff.  

We are accepting the pull request into the master branch. We also hope to merge the rgcVisualize branch into the master today.  These have been around and used long enough, and this merge will let us simplify the project.

i.e., LGTM (with @jamesgolden1)

**Comment by npcottaris** [comment]
Dont merge to master yet please.
Currently working on this branch.

Nicolas

On Oct 28, 2016, at 2:35 PM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:


Great stuff.

We are accepting the pull request into the master branch. We also hope to merge the rgcVisualize branch into the master today. These have been around and used long enough, and this merge will let us simplify the project.

i.e., LGTM (with @jamesgolden1<https://github.com/jamesgolden1>)

**Comment by wandell** [comment]
I restored the branch on the site.

I think you can still push to the branch and then just merge your changes again.

Sorry for any trouble.

**Comment by npcottaris** [comment]
Thanks!


On Oct 28, 2016, at 2:52 PM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:


I restored the branch on the site.

I think you can still push to the branch and then just merge your changes again.

Sorry for any trouble.

**Comment by jamesgolden1** [comment]
@npcottaris, @wandell and I are interested in why the photons fields of the OIs are stored in their own properties in an oiSequence object, in addition to the OIs being stored. Would it be possible to get rid of the dedicated photons field in the oiSequence object?

**Comment by npcottaris** [comment]
Yes. I can do that.

**Comment by DavidBrainard** [comment]
Just to double check, these aren't there to allow fast computation of multiple noise draws for the same stimuli?

**Comment by npcottaris** [comment]
I did some benchmarking on this.

- For a 148 frame sequence, simply extracting the frames takes 7 seconds when using the stored photons property (extracted at init time) vs 13 seconds when asking the oi to return the photons on the fly. So storing the photons cuts the time to get the frames by half.

- In an actual `computeForOIsequence` run with the same `oiSequence`, 50 responses instances and a mosaic of 130x130 cones the difference is 2.88 minutes vs 2.97 minutes. So in practice there is not a real benefit of storing the photons. This is because the `computeForOIsequence` is coded smartly and does not keep asking for the `oiSequence` frame for each response instance. [self pat on the back] 

At any rate, please let me know if you want the photons property removed.

**Pull request merged**
