### PR TITLE
Datamove

### PR DESCRIPTION
**Pull request by DavidBrainard**
I did some rearranging as a start to thinking about how to document data and encapsulate and unify how we read key data.

a) Moved the data folder out of the isettools folder and into the top level of isetbio.  This separate the data a bit more from the code. 

b) Wrote isetbioDataFolder, which points to the data tree.  Changed all reads from the data folder to use this.

c) Wrote ieRunAllTutorials, which runs all of the tutorials.  I did this to check that they weren't broken because of the above, and fixed a few that were. 

d) Step c) revealed a number of broken tutorials.  Many of these are because the switch to layers is in progress, as many of bipolar and rgc tutorials have not been updated for that and are now broken.  I moved all broken tutorials into an "underDevelopment" directories inside of their respective directories.  The ieRunAllTutorials script is set up to skip these (although it lists them.)

e) Merged current master branch into this, and verified that validations all pass and remaining tutorials all run without error.

@wandell Can you review and merge, unless something in the above is objectionable?  This change might break code outside of isetbio that finds data directly -- we were not doing that in our projects and I think almost all the data reads already go through intermediate functions so I'm not too worried.  But something to be aware of.

### CODE REVIEW

**Comment by wandell** [comment]
Even before checking, I can see how moving the data folder might cause a lot of problems.  There were many cases in my world when I used fullfile(isetRootPath,'data',...) to load a data set.  Maybe D65.mat or cones.mat are used for some calculation.   Perhaps you caught all of these reads from within ISET.  But what about the external scripts?

**Comment by DavidBrainard** [comment]
Sigh.  I was hoping that there were none, as per note at end of PR....  It is exactly all instances of this sort that I am hoping we can find and eventually purge, so that we have a hope of localizing our data reads.

But, the reason I did this on a branch is exactly as you describe.

If there are a whole lot of places outside isetbio where you call fullfile(isetRootPath,'data',...), what I will do is move data back into isettools and modify isetbioDataPath to point at it there.  Then we can merge this branch.  And then as we get a chance we can change your code over to use isetbioDataPath.  And then it will at least be easy to move the data dir in the future.  If you point me at the repositories I can take this on.

More generally, what I want to think about is how to localize and clarify how and where we read data....

**Comment by wandell** [comment]
Here is how to find the files that use fullfile(isetRootPath,'data' 
inside the isetbio directory.  It would take about an hour to eliminate them, replacing with isetDataPath(... additional arguments).

Then you could replace fullfile(isetRootPath,'data',....) with isetDataPath( ....).  External scripts would have to change, but there probably aren't too many that rely on the current data directory.


screen shot 2017-07-25 at 5 54 58 pm

**Comment by DavidBrainard** [comment]
Ah, my pull request comments were not sufficiently clear.  This is exactly what I already did in the branch I asked you to pull – it should already be all set. (I use TextWrangler, which is free and has a very easy to use function that will search and replace down an entire tree.)

My worry was not what’s inside the isetbio tree, it was external functions as you noted.  If you don’t think there are many of those in your code (I couldn’t find any in mine), then we should be good to do with this PR.

**Comment by wandell** [comment]
Well given my misunderstanding, let's keep it open.  

I am still struggling to document and make the bipolar/rgc changes go well. James and I spent a couple of hours on stuff that was very confusing, and I am still not sure we judged correctly.

But if moving the data directory seems important to you, we can try after the dust settles.

**Pull request closed without merging**
