### PR TITLE
Debug cone current computation for OIS

### PR DESCRIPTION
**Pull request by elinekupers**
Hi all,

I've been working on debugging the cone current computation for optical image sequences.  I am using the osLinear model, where the bioPhys model is used to 'warm up' the linear filters.  The absorption computation works fine (as far as my knowledge goes), but I figured that for the cone current computation, there are a couple of bugs. I tried to fix bug 1 and 2, I don't know how to fix bug 3. I also attached a small script with example code, that runs on it's own with my current fork (https://github.com/elinekupers/isetbio).

1. The back ground rate for the three cone classes is recomputed several times, instead of used as an input to warm up the bioPhys model.
2.  To convert the absorption array (x,y,t) to (x*y,t), the function
`RGB2XWFormat(cMosaic.absorptions) `
does not handle the time dimension. My assumption is that this function is only working when having an OI, with multiple wavelengths in the third dimension (instead of having time samples for the OIS).  I left the function as is, and made an (ugly) hack to check for a time dimension in the coneMosaic object. We probably want to create a new function that handles the two types (OI versus OIS) more gracefully.

3. The linear filters are made with an impulse function based on a separate small "mock" coneMosaic (within isettools/cones/outersegment/@osLinear/linearFilters.m). This impulse function is based on an integration time of 1 ms. When these filters are interpolated back to the original time step of the absorption rates (see line 92-102 in isettools/cones/outersegment/@osLinear/osCompute.m):

```
%% Interpolate the stored lmsFilters to the time base of the absorptions
    osTimeAxis    = obj.timeAxis;
    absTimeAxis   = cMosaic.interpFilterTimeAxis;
    interpFilters = zeros(numel(absTimeAxis),3);
    for ii=1:3
        % Interpolation assumes that we are accounting for the time sample bin
        % width elsewhere.  Also, we extrapolate the filters with zeros to make
        % sure that they extend all the way through the absorption time axis.
        % See the notes in s_matlabConv2.m for an explanation of why.
        interpFilters(:,ii) = interp1(osTimeAxis(:),lmsFilters(:,ii),absTimeAxis(:),'linear',0);
    end
``` 

The osTimeAxis and absTimeAxis are based on the small cone "mock" coneMosaic. These time axes have different length and integration time steps than my initial coneMosaic. So if I don't use 1 ms time steps and a 400 ms stimulus, I have mismatch in number of time samples and absolute length of one time sample, which I believe, results in an incorrect cone current computation. I don't know how to fix this last bug, but I think it has to do something with letting the experimenter specify the cMosaic.interpFilterTimeAxis.

Please feel free to cancel my pull request and let me know if there is something I misunderstood or need to fix.

Thanks!

```
%% exampleConeCurrent

% Testing cone current computation with a stand alone simple script
% by EK (April 2018)

%% 1. Set up scene parameters

nTrials = 1;

% Scene field of view
sparams.fov      = 2;   % scene field of view in degrees (diameter)
sparams.distance = 0.57;    % Meters

% Gabor parameters
P(1:2)        = harmonicP;  % Standard Gabor
P(1).contrast = 0;

% Temporal properties of one trial
tseries = ieScale(fspecial('gaussian',[1,50],15),0,1);

% Make a default Optical Image Sequence.
[ois, scene] = oisCreate('harmonic','blend', tseries, 'testParameters', P, 'sceneParameters', sparams);

% We make sure that the number of time points in the eye movement sequence
% matches the number of time points in the optical image sequence
tSamples         = ois.length;

%% 2. Make cone mosaic for a given eccentricity and polar angle

% Pick an eye
whichEye = 'left';

% Convert degrees to meters
deg2m = 0.3 * 0.001; % (adjusted to the default in isetbio)

% Specify retinal location where stimulus is presented
cparams.eccentricity = 10;             % Visual angle of stimulus center, in deg
polarAngleDeg        = 0;              % Polar angle of stimulus, in radians, so right from fixation, horizontal meridian
cparams.polarAngle   = deg2rad(polarAngleDeg);   % Polar angle (radians): 0 is right, pi/2 is superior, pi is left, 3*pi/2 inferior

% Cone mosaic field of view in degrees
cparams.cmFOV        = sparams.fov; % degrees

% Compute x,y position in m of center of retinal patch from ecc and angle
[x, y] = pol2cart(cparams.polarAngle, cparams.eccentricity);
x = x * deg2m;  y = y * deg2m;

% Create cone mosaic
cMosaic = coneMosaic('center', [x, y], 'whichEye', whichEye);

% Set the field of view (degrees)
cMosaic.setSizeToFOV(cparams.cmFOV);

% Add photon noise
cMosaic.noiseFlag = 'random';

% Set outer segment to be computed with linear filters
cMosaic.os = osLinear;

% Should/Can we specify interpFilterTimeAxis? cMosaic.interpFilterTimeAxis = 1:length(tseries);

%% 3. Add eyemovements
cparams.em        = emCreate;
cparams.em.emFlag = [1 1 0]; % Include tremor and drift, no ms

% Generate the eye movement paths in units of cone samples. Set the
% time sample to 2x the actual time, so that the eye does not
% always start at 0,0. We will then clip after generating the eye
% movements.
emPaths  = cMosaic.emGenSequence(tSamples*2, 'nTrials', nTrials, ...
    'em', cparams.em); % path is in terms of cones shifted
emPaths = emPaths(:, end/2+1:end,:);
cMosaic.emPositions = squeeze(emPaths(1,:,:));

%% 4. Compute absorptions and cone current

[absorptions, current, interpFilters, meanCur] = cMosaic.compute(ois, 'currentFlag', true, 'emPaths', emPaths);

% Check outputs
cMosaic.window;
```

### CODE REVIEW

**Comment by wandell** [comment]
Sorry this has been hanging around so long without getting attended to.

Concerning point (1), it is good if we recomputed multiple times and you prevent that. 

Concerning point(2), the RGB2XWFormat() should work.  There is something else wrong.  Maybe the absorptions have multiple trials and a singleton dimension?  So the absorptions might need a squeeze()?  Also, absorptions never have a wavelength dimension.  So, we should look a little more closely.

Consistency with the time axes has been plaguing us.  I will try to understand the issue.  This would be a good moment for me to write a wiki page documenting how we manage the time axis from OIS to coneMosaic and its various constituents.

This comment is intended just to get the conversation started about the pull request.  I didn't do anything.

**Comment by elinekupers** [comment]
I've looked into the third point (discrepancy between stimulus and cone mosaic time axis), using an old issue pointing out the same: https://github.com/isetbio/isetbio/issues/292, and the most recent version of the master branch.

In issue 292, @npcottaris pointed out that the number of eye movements generated should be based on cMosaic.integrationTime, not the OIS time axis. Then the absorption count (even though it states pAmps in the figure, I believe this should be absorption count, since that is the variable used), was plotted against the responseTimeAxis (= cMosaic.timeAxis).

In the 292 issue, the number of eyemovements were defined as 
`theEMPaths = cMosaic.emGenSequence(nFrames, 'nTrials', nTrials);`

where:
`nFrames = length(oiTimeAxis);`

This results in 51 frames, but if I use the alternative suggested function: 
`eyeMovementsNum = theOIsequence.maxEyeMovementsNumGivenIntegrationTime(cMosaic.integrationTime);`
The result is 204 frames..

I used the same code as in issue 292, except using a Gabor stimulus with a gaussian temporal window. And used either the 'maxEyeMovementsNumGivenIntegrationTime' function or the number of frames based on the ois. 

With the first function, I get reasonable cone absorption rates, but I am not sure about the cone currents. My question is, should I expect a small change (less than 1 pAmp) in the cone currents for my relatively short stimulus presentation? Or did I use the incorrect amount for the first argument of the 'emGenSequence' and should I use nFrames?

These are the absorptions and currents when I define the emPaths as:
`emPaths  = cMosaic.emGenSequence(eyeMovementsNum, 'nTrials', nTrials);
`
screen shot 2018-05-29 at 6 10 27 pm

And this is when I define emPaths with the nFrames:
`emPaths  = cMosaic.emGenSequence(nFrames, 'nTrials', nTrials);
`
screen shot 2018-05-29 at 6 27 47 pm

Here is the code to reproduce the images:
```
%% exampleConeCurrent

% Testing cone current computation with a stand alone simple script
% by EK (May 29, 2018)

%% 1. Set up scene parameters

nTrials = 100;

% Scene field of view
sparams.fov      = 2;   % scene field of view in degrees (diameter)
sparams.distance = 0.57;    % Meters

% Gabor parameters
P(1:2)        = harmonicP;  % Standard Gabor
P(1).contrast = 0;

% Temporal properties of one trial
tseries = ieScale(fspecial('gaussian',[1,50],15),0,1);

% Make a default Optical Image Sequence.
[ois, scene] = oisCreate('harmonic','blend', tseries, 'testParameters', P, 'sceneParameters', sparams);

% We make sure that the number of time points in the eye movement sequence
% matches the number of time points in the optical image sequence
tSamples         = ois.length;

% Check ois time axis, i.e. number of frames
oiTimeAxis       = ois.timeAxis;
nFrames          = length(oiTimeAxis);

%% 2. Make cone mosaic for a given eccentricity and polar angle

% Pick an eye
whichEye = 'left';

% Convert degrees to meters
deg2m = 0.3 * 0.001; % (adjusted to the default in isetbio)

% Specify retinal location where stimulus is presented
cparams.eccentricity = 10;             % Visual angle of stimulus center, in deg
polarAngleDeg        = 0;              % Polar angle of stimulus, in radians, so right from fixation, horizontal meridian
cparams.polarAngle   = deg2rad(polarAngleDeg);   % Polar angle (radians): 0 is right, pi/2 is superior, pi is left, 3*pi/2 inferior

% Cone mosaic field of view in degrees
cparams.cmFOV        = sparams.fov; % degrees

% Compute x,y position in m of center of retinal patch from ecc and angle
[x, y] = pol2cart(cparams.polarAngle, cparams.eccentricity);
x = x * deg2m;  y = y * deg2m;

% Create cone mosaic
cMosaic = coneMosaic('center', [x, y], 'whichEye', whichEye);

% Set the field of view (degrees)
cMosaic.setSizeToFOV(cparams.cmFOV);

% Add photon noise
cMosaic.noiseFlag = 'random';

% Set outer segment to be computed with linear filters
cMosaic.os = osLinear;

eyeMovementsNum = ois.maxEyeMovementsNumGivenIntegrationTime(cMosaic.integrationTime);

%% 3. Add eyemovements

emPaths  = cMosaic.emGenSequence(eyeMovementsNum, 'nTrials', nTrials); % path is in terms of cones shifted


%% 4. Compute absorptions and cone current

[absorptions, current, interpFilters, meanCur] = cMosaic.computeForOISequence(ois, 'currentFlag', true, 'emPaths', emPaths);



%% 5. Visualize

% Check outputs
% cMosaic.window;

% Define response axis
responseTimeAxis = cMosaic.timeAxis;

% Indices to 3 cone classes
lcones = cMosaic.pattern == 2;
mcones = cMosaic.pattern == 3;
scones = cMosaic.pattern == 4;

absorptions1 = permute(absorptions, [2 3 4 1]);
current1 = permute(current, [2 3 4 1]);
sz = size(absorptions1);
absorptions1 = reshape(absorptions1, sz(1)*sz(2), sz(3), sz(4));
current1 = reshape(current1, sz(1)*sz(2), sz(3), sz(4));

% Compute absorptions and current per cone class as cones x tPoints x trials
l_absorptions = absorptions1(lcones,:,:);
m_absorptions = absorptions1(mcones,:,:);
s_absorptions = absorptions1(scones,:,:);

l_curr = current1(lcones,:,:);
m_curr = current1(mcones,:,:);
s_curr = current1(scones,:,:);



% Summarize each cone class as the mean time series across cones and across
% trials
l_absorptions_mn = mean(mean(l_absorptions,3));
m_absorptions_mn = mean(mean(m_absorptions,3));
s_absorptions_mn = mean(mean(s_absorptions,3));

l_current_mn = mean(mean(l_curr,3));
m_current_mn = mean(mean(m_curr,3));
s_current_mn = mean(mean(s_curr,3));

% plot
figure(2); clf
subplot(4,1,1)
plot(oiTimeAxis,ois.modulationFunction,'k')
hold on; grid on
ylabel('magnitude')
xlabel('Time (s)')
title('Stimulus modulation function')

subplot(4,1,2)
plot(responseTimeAxis,l_absorptions_mn,'r', 'LineWidth', 1.5)
hold on; grid on
ylabel('Photon absorption count')
xlabel('Time (s)')
title('L cones')

subplot(4,1,3)
plot(responseTimeAxis,m_absorptions_mn,'g', 'LineWidth', 1.5)
hold on; grid on
ylabel('Photon absorption count')
xlabel('Time (s)')
title('M cones')

subplot(4,1,4)
plot(responseTimeAxis,s_absorptions_mn,'b','LineWidth', 1.5)
hold on; grid on
ylabel('Photon absorption count')
xlabel('Time (s)')
title('s cones')


%% plot Currents
figure(3); clf;
subplot(4,1,1)
plot(oiTimeAxis,ois.modulationFunction,'k')
grid on
ylabel('magnitude')
xlabel('Time (s)')
title('Stimulus modulation function')

subplot(4,1,2); hold on; grid on
plot(responseTimeAxis,l_current_mn,'r', 'LineWidth', 1.5)
ylabel('pAmps')
xlabel('Time (s)')
title('L cones')

subplot(4,1,3); hold on; grid on
plot(responseTimeAxis,m_current_mn,'g', 'LineWidth', 1.5)
ylabel('pAmps')
xlabel('Time (s)')
title('M cones')

subplot(4,1,4); hold on; grid on
plot(responseTimeAxis,s_current_mn,'b','LineWidth', 1.5)
ylabel('pAmps')
xlabel('Time (s)')
title('s cones')
```

**Comment by npcottaris** [comment]
Hi Eline,

I looked at your script and corrected it.  The figure below shows the output of the fixed script. 
The top plot shows the stimulus modulation,  the middle plot shows the mean (over 30 trials) and std of the isomerization response for the best L-, M-, and S-cone, and the bottom plot shows  the mean (over 30 trials) photocurrent response for the same L-, M-, and S-cones.

eline

Here is the fixed script.
```
% Set up scene
sparams.fov      = 2;   % scene field of view in degrees (diameter)
sparams.distance = 0.57;    % Meters

% Gabor parameters
P(1:2) = harmonicP;  % Standard Gabor
P(1).contrast = 0;

% Stimulus temporal properties
stimDurationSeconds = 200/1000;  % 200 milliseconds
stimRefreshRate = 10/1000;       % 100 Hz display
stimSampleTimes = (0:ceil(stimDurationSeconds/stimRefreshRate))*stimRefreshRate;
stimModulationEnvelope = ieScale(fspecial('gaussian',[1,numel(stimSampleTimes)],3),0,1);

% Make an optical image sequence of the stimulus
[ois, scene] = oisCreate('harmonic','blend', stimModulationEnvelope, ...
    'sampleTimes', stimSampleTimes, ...
    'testParameters', P, ...
    'sceneParameters', sparams);

% Create cone mosaic
cMosaic = coneMosaic('center', [0,0], 'whichEye', 'left');

% Set the field of view (degrees)
cMosaic.setSizeToFOV(sparams.fov);

% Add photon noise
cMosaic.noiseFlag = 'random';

% Set outer segment to be computed with linear filters
cMosaic.os = osLinear;

% Set the desired integration time, here 5 milliseconds
cMosaic.integrationTime = 5/1000;

% Compute the # of eye movements
% Eye movements are sampled according to the integration time of the cone
% mosaic. So if, the integration time is 5 msec, and the OIsequence is 1
% second long, we need to generate 200 eye movements. To compute this use
% the maxEyeMovementsNumGivenIntegrationTime() method of the oiSequence.
eyeMovementsNum = ois.maxEyeMovementsNumGivenIntegrationTime(cMosaic.integrationTime);

% Generate eye eyemovements for nTrials
nTrials = 30;
emPaths = cMosaic.emGenSequence(eyeMovementsNum, ...
    'nTrials', nTrials, ...
    'microsaccadetype', 'none');

% Compute absorptions and photocurrents
[absorptions, photocurrents, interpFilters, meanCur] = ...
    cMosaic.computeForOISequence(ois, ...
        'currentFlag', true, ...
        'emPaths', emPaths);

% Visualize the mean response of the best responding L-, M- and S-cone
% Compute absorptions and current per cone class as cones x tPoints x trials
absorptions1 = permute(absorptions, [2 3 4 1]);
current1 = permute(photocurrents, [2 3 4 1]);
[nRows, mCols, tBins, nTrials] = size(absorptions1);
absorptions1 = reshape(absorptions1, [nRows*mCols tBins nTrials]);
current1 = reshape(current1, [nRows*mCols tBins nTrials]);

% Find indices of cones for each of the 3 cone types
lcones = cMosaic.pattern == 2;
mcones = cMosaic.pattern == 3;
scones = cMosaic.pattern == 4;

% Find indices of the best responding L, M ans S-cone
l_absorptions = absorptions1(lcones,:,:);
m_absorptions = absorptions1(mcones,:,:);
s_absorptions = absorptions1(scones,:,:);
l_curr = current1(lcones,:,:);
m_curr = current1(mcones,:,:);
s_curr = current1(scones,:,:);

[~,maxIndex] = max(l_absorptions(:));
[maxLconeIndex, ~, ~] = ind2sub(size(l_absorptions), maxIndex);
[~,maxIndex] = max(m_absorptions(:));
[maxMconeIndex, ~, ~] = ind2sub(size(m_absorptions), maxIndex);
[~,maxIndex] = max(s_absorptions(:));
[maxSconeIndex, ~, ~] = ind2sub(size(s_absorptions), maxIndex);

% Compute mean over reps of best responding L-cone
meanLconeResponse = squeeze(mean(l_absorptions(maxLconeIndex,:, :),3));
stdLconeResponse = squeeze(std(l_absorptions(maxLconeIndex,:, :),0, 3));

% Compute mean over reps of best responding M-cone
meanMconeResponse = squeeze(mean(m_absorptions(maxMconeIndex,:, :),3));
stdMconeResponse = squeeze(std(m_absorptions(maxMconeIndex,:, :),0, 3));

% Compute mean over reps of best responding S-cone
meanSconeResponse = squeeze(mean(s_absorptions(maxSconeIndex,:, :),3));
stdSconeResponse = squeeze(std(s_absorptions(maxSconeIndex,:, :),0, 3));

% Obtain the response time axes in milliseconds
responseTimeAxis = cMosaic.timeAxis * 1000;
tTicks = (0:stimRefreshRate:10)*1000;

% Render results
hFig = figure(10); clf;
set(hFig, 'Position', [10 10 750 1100]);
subplot(3,1,1);
% Check ois time axis, i.e. number of frames
stairs(ois.timeAxis*1000,ois.modulationFunction,'k', 'LineWidth', 1.5)
set(gca, 'XLim', [responseTimeAxis(1) responseTimeAxis(end)], 'XTick', tTicks);
grid on
set(gca, 'FontSize', 12);
ylabel('stimulus modulation', 'FontWeight', 'bold')
xlabel('time (ms)', 'FontWeight', 'bold')

subplot(3,1,2)
plot(responseTimeAxis,meanLconeResponse ,'r-', 'LineWidth', 1.5); hold on;
plot(responseTimeAxis,meanLconeResponse+stdLconeResponse ,'r:', 'LineWidth', 1.0);
plot(responseTimeAxis,meanLconeResponse-stdLconeResponse ,'r:', 'LineWidth', 1.0);

plot(responseTimeAxis,meanMconeResponse,'g-', 'LineWidth', 1.5); hold on;
plot(responseTimeAxis,meanMconeResponse+stdMconeResponse ,'g:', 'LineWidth', 1.0);
plot(responseTimeAxis,meanMconeResponse-stdMconeResponse ,'g:', 'LineWidth', 1.0);

plot(responseTimeAxis,meanSconeResponse,'b-', 'LineWidth', 1.5); hold on;
plot(responseTimeAxis,meanSconeResponse+stdSconeResponse ,'b:', 'LineWidth', 1.0);
plot(responseTimeAxis,meanSconeResponse-stdSconeResponse ,'b:', 'LineWidth', 1.0);

set(gca, 'XLim', [responseTimeAxis(1) responseTimeAxis(end)], 'XTick', tTicks);
grid on
set(gca, 'FontSize', 12);
xlabel('time (ms)', 'FontWeight', 'bold')
ylabel('isomerizations', 'FontWeight', 'bold');

subplot(3,1,3);
plot(responseTimeAxis,squeeze(mean(l_curr(maxLconeIndex,:, :),3)),'r', 'LineWidth', 1.5); hold on
plot(responseTimeAxis,squeeze(mean(m_curr(maxMconeIndex,:, :),3)),'g', 'LineWidth', 1.5);
plot(responseTimeAxis,squeeze(mean(s_curr(maxSconeIndex,:, :),3)),'b', 'LineWidth', 1.5);
set(gca, 'XLim', [responseTimeAxis(1) responseTimeAxis(end)]);
set(gca, 'XLim', [responseTimeAxis(1) responseTimeAxis(end)], 'XTick', tTicks);
grid on
set(gca, 'FontSize', 12);
xlabel('time (ms)', 'FontWeight', 'bold')
ylabel('photocurrent (pAmps)', 'FontWeight', 'bold');


% Visualize the oiSequence as a montage
%ois.visualize('montage');
```

Let me know if you need any more help.

**Comment by npcottaris** [comment]
Eline, you should run the above script in the main branch of isetbio.

**Comment by elinekupers** [comment]
Thanks for your help and quick response, Nicholas! 
I was wondering where the 5 ms integration time for the cMosaic came from.
Is that because you have a 200 ms stimulus duration? And therefore a 1/0.2 = 5? 

Or does it also depend on the sampling rate of your stimulus presentation?

**Comment by npcottaris** [comment]
You can set the integration time to whatever value you want, INDEPENDENTLY of the stimulus duration.
However, I would recommend to not set it longer than 5 milliseconds, because  the temporal impulse response of the outersegment is going to be subsampled using that integration time, and longer integration times will result in a choppy impulse response function. I set it to 5 msec to speed up the execution time. For production work, my recommendation is to set it to 1 or 2 milliseconds.

**Comment by elinekupers** [comment]
Ok, that makes things clear. Just to make sure that I understand the logic of changing certain parameters:

- cMosaic.integrationTime has a default of 5 ms, but can be set to anything. This time can be shorter, resulting in (1) finer sampling of the absorption rate and photocurrent, therefore (2) a smaller absorption rate and photocurrent, (3) it is also more computationally expensive. 

- The number of eye movements depend on the cMosaic.integrationTime and the stimulus duration, where emPaths should have the dimensions:
nTrials * [(stimDur / cMosaic.integrationTime)+cMosaic.integrationTime] * [x,y]

- The stimulus sampling rate can be set to anything, where a finer stimulus sampling rate results in smoother temporal window. In this script, it results in a sharper temporal window, which give slightly smaller amounts of cone isomerizations, and a lot smaller photocurrent fluctuations.

- In general, you have a short stimulus duration (< 70 ms) or small temporal window, you will not see large differences within individual cone photocurrent (if using the osLinear filters) because the impulse response function of these filters are sluggish: Start to ramp after ~80 ms, peaking at ~130 ms for L and M cones and ~200 ms to get back to baseline.

Thanks again!

**Comment by npcottaris** [comment]
1. Absorption rate **does not** change when you change the integration time, but the absorption counts **does change**, because `counts = rate x integrationTime`. The photocurrent changes only because of discretization effects on the outer segment impulse response, otherwise it only depends on the absorption rate, which again does not change with integration time. The benefit of having shorter integration time is that the dynamics of the outer segment and of the eye movements, (both of which are tied to the integration time) are better approximations of the ideal dynamics. The drawback is that computation time increases as the integration time decreases.

2. The `emPaths` dimensions should be:  `nTrials   X   ceil(stimDur/cm.integrationTime)   X 2`

3. The stimulus sampling rate should approximate the display temporal dynamics. For a 100 Hz display set it to 10 msec.  But yes, you can set it to anything.

4. I am not sure I understand your fourth point. The outer segment filter is somewhat biphasic, so temporally bandpass. So stimuli with temporal modulations outside of this bandpass will result in lower photocurrents compared to stimuli within that bandpass. 

Also note that the outer segment temporal filters are biophysically derived, so their amplitude and shape depends strongly on the mean isomerization rate (which in turn depends on the stimulus mean luminance). The higher the isomerization rate, the lower their amplitude and, therefore, the lower the photocurrent modulation, as seen in the figure below. This is modeling luminance adaptation. See `t_linearFilters` tutorial for more info.

oslinearfilters

**Comment by npcottaris** [comment]
I provided detailed instructions to Eline on how to deal with her code's timing issues, which was the main issue. One other issue, was some sort of optimization. I have not looked at the proposed solution so I am hesitant to merge without detailed testing. At this point my preference is for this to PR to be deleted.

Eline?

**Comment by elinekupers** [comment]
I had three issues, where the last point was not a bug but something related to my own misunderstanding (which resulted in a long back and forth in this thread). 

As Nicholas said, other two points are not bugs, but more for optimization and making the code more OIS friendly (versus OI). Because the buglet fixes are written in a hacky way, I am inclined to say that we can cancel this pull request. Although I do believe that it is worth going over the photo current script and clarify some things, for example what the RGB2XWFormat is doing and what format your OIS data gets transformed into when running this code.

**Comment by DavidBrainard** [comment]
OK, closing this long issue.  Eline, maybe you can post a separate issue that points to the place where we should clarify the documentation.  Then at least we won't lose track of the idea that that would be helpful.

**Pull request closed without merging**
