### PR TITLE
Bug in opticsGet "deg per dist" or "dist per deg" 

### PR DESCRIPTION
**Pull request by tlian7**
I found a small bug where _tan_ was accidentally written as _atan_. I discovered this because opticsDefocusCore.m and related scripts were not producing reasonable results. 

Notifying here as a pull request in case this bug might affect other (more) important parts of the pipeline.

### CODE REVIEW

**Comment by npcottaris** [comment]
Wow ... A core bug after so many years ... Well, all validations are passing on the tangentBug branch, and this is our strongest tool (after our intuition) for assessing consistency.

Obviously some computations will be affected, but at least not the ones tested by the validations, which are the most commonly used.


Holding off on merging into the master until David and Brian sign off on this.


Thank you Trisha.


Best,

Nicolas

________________________________
From: Trisha Lian ***@***.***>
Sent: Monday, April 12, 2021 8:52 PM
To: isetbio/isetbio ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [isetbio/isetbio] Bug in opticsGet "deg per dist" or "dist per deg" (#405)


I found a small bug where tan was accidentally written as atan. I discovered this because opticsDefocusCore.m and related scripts were not producing reasonable results.

Notifying here as a pull request in case this bug might affect other (more) important parts of the pipeline.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/isetbio/isetbio/pull/405

Commit Summary

  *   Fixed an "atan" <--> "tan" bug. Discovered because opticsDefocusCore.m was not working properly.

File Changes

  *   M isettools/opticalimage/optics/opticsGet.m<https://github.com/isetbio/isetbio/pull/405/files#diff-a4cb44680c0bd45ca7428b810c90704fb4645b81be948707e05560dd93384682> (10)

Patch Links:

  *   https://github.com/isetbio/isetbio/pull/405.patch
  *   https://github.com/isetbio/isetbio/pull/405.diff

**Comment by DavidBrainard** [comment]
I'd say write an example in the function using our standard examples syntax that verifies that dist per deg yields about 0.3 mm for 1 degree and the default human oi, and that the two functions self invert.  The example can have checks on those two things to reasonable precision. If these pass, merge away.  The example will then in the future be tested anytime we run ieRunExamplesAll.  Might want to check that isetcam doesn't include this functionality/bug.

**Comment by wandell** [comment]
That seems right.

And I will  try to understand why we were getting the correct answers to the mouse and human cases last week.  There must be a different computational path.

Brian Wandell
Stein Family Chair
Stanford University
Http://www.stanford.edu/~wandell
________________________________

**Comment by DavidBrainard** [comment]
I think there are a lot of computational paths to this.  I didn't know about these particular
functions, I don't think.

From: Brian Wandell ***@***.***>
Reply-To: isetbio/isetbio ***@***.***>
Date: Tuesday, April 13, 2021 at 11:28 AM
To: isetbio/isetbio ***@***.***>
Cc: "Brainard, David H" ***@***.***>, Comment ***@***.***>
Subject: Re: [isetbio/isetbio] Bug in opticsGet "deg per dist" or "dist per deg" (#405)

That seems right.

And I will try to understand why we were getting the correct answers to the mouse and human cases last week. There must be a different computational path.

Brian Wandell
Stein Family Chair
Stanford University
Http://www.stanford.edu/~wandell
________________________________

**Comment by wandell** [comment]
Disturbing, sigh.

The answer to oi = oiCreate(‘human’) or just oi = oiCreate(); ISETCam is 296 um and in ISETBio the answer is 0.76 meters.  Looking at the code, I think there is a right parenthesis missing in the ISETBio code (I think).  Will check more closely with Zheng later today.

Brian

From: David Brainard ***@***.***>
Date: Tuesday, April 13, 2021 at 8:29 AM
To: isetbio/isetbio ***@***.***>
Cc: Brian A Wandell ***@***.***>, Comment ***@***.***>
Subject: Re: [isetbio/isetbio] Bug in opticsGet "deg per dist" or "dist per deg" (#405)
I think there are a lot of computational paths to this. I didn't know about these particular
functions, I don't think.

From: Brian Wandell ***@***.***>
Reply-To: isetbio/isetbio ***@***.***>
Date: Tuesday, April 13, 2021 at 11:28 AM
To: isetbio/isetbio ***@***.***>
Cc: "Brainard, David H" ***@***.***>, Comment ***@***.***>
Subject: Re: [isetbio/isetbio] Bug in opticsGet "deg per dist" or "dist per deg" (#405)

That seems right.

And I will try to understand why we were getting the correct answers to the mouse and human cases last week. There must be a different computational path.

Brian Wandell
Stein Family Chair
Stanford University
Http://www.stanford.edu/~wandell
________________________________

**Comment by tlian7** [comment]
Hi @wandell, I think the error is what I fixed in this pull request (see [commit](https://github.com/isetbio/isetbio/pull/405/commits/72e85f7684a6701247c979642393edc0a0db7bba).) The tangent was accidentally written as atangent. When I run these lines in this corrected branch ("tangentBug") I get the right result, 0.2967 mm.

`oi = oiCreate('human');
optics = oiGet(oi,'optics');
opticsGet(optics,'dist per deg')*10^3
`

**Comment by wandell** [comment]
Thanks.

From: Trisha Lian ***@***.***>
Date: Tuesday, April 13, 2021 at 2:08 PM
To: isetbio/isetbio ***@***.***>
Cc: Brian A Wandell ***@***.***>, Mention ***@***.***>
Subject: Re: [isetbio/isetbio] Bug in opticsGet "deg per dist" or "dist per deg" (#405)

Hi @wandell<https://github.com/wandell>, I think the error is what I fixed in this pull request (see commit<https://github.com/isetbio/isetbio/pull/405/commits/72e85f7684a6701247c979642393edc0a0db7bba>.) The tangent was accidentally written as atangent. When I run these lines in this corrected branch ("tangentBug") I get the right result, 0.2967 mm.

oi = oiCreate('human'); optics = oiGet(oi,'optics'); opticsGet(optics,'dist per deg')*10^3

**Comment by tlian7** [comment]
> I'd say write an example in the function using our standard examples syntax that verifies that dist per deg yields about 0.3 mm for 1 degree and the default human oi, and that the two functions self invert. The example can have checks on those two things to reasonable precision. If these pass, merge away. The example will then in the future be tested anytime we run ieRunExamplesAll. Might want to check that isetcam doesn't include this functionality/bug.

Hi @DavidBrainard, I'm trying to add this check before merging this pull request. Although there is a `ieRunExamplesAll` script, there is no `ExecuteExamplesInDirectory` function in ISETBio. It exists in ISETCam though. Am I just missing this function, or is it only an ISETCam thing?

**Comment by DavidBrainard** [comment]
Ah.  You need the ExampleTestToolbox on your path.  It's in the isetbio organization on github.  It's possible you also need the UnitTestToolbox,
but I don't think so for the examples.  (You'll need the UnitTestToolbox to run ieRunTutorialsAll, however).

Best,

David

From: Trisha Lian ***@***.***>
Reply-To: isetbio/isetbio ***@***.***>
Date: Wednesday, April 14, 2021 at 4:55 PM
To: isetbio/isetbio ***@***.***>
Cc: "Brainard, David H" ***@***.***>, Mention ***@***.***>
Subject: Re: [isetbio/isetbio] Bug in opticsGet "deg per dist" or "dist per deg" (#405)


I'd say write an example in the function using our standard examples syntax that verifies that dist per deg yields about 0.3 mm for 1 degree and the default human oi, and that the two functions self invert. The example can have checks on those two things to reasonable precision. If these pass, merge away. The example will then in the future be tested anytime we run ieRunExamplesAll. Might want to check that isetcam doesn't include this functionality/bug.

Hi @DavidBrainard<https://github.com/DavidBrainard>, I'm trying to add this check before merging this pull request. Although there is a ieRunExamplesAll script, there is no ExecuteExamplesInDirectory function in ISETBio. It exists in ISETCam though. Am I just missing this function, or is it only an ISETCam thing?

**Comment by tlian7** [comment]
Added example check to the top of `opticsGet`. `ExecuteExamplesInFunction('opticsGet.m')` runs successfully. Merging pull request now!

**Pull request merged**
