### PR TITLE
NewLinear

### PR DESCRIPTION
**Pull request by gbarajas125**
Signed-off-by: Nicolas Cottaris <cottaris@sas.upenn.edu>

### CODE REVIEW

**Comment by wandell** [comment]
@npcottaris  - I ran the v_osTimeSteps.  LGTM, though it is very long and slow for a validation script.

Still, I propose that we merge newLinear into master and fix up the conflict. I am ready any time.  Then I think we should start little projects to
   
    *  Edit the wiki to describe what we think
    *  Simplify the validation scripts
    *  Try to understand the difference between validation and tutorial

Concerning the scripts - I think that general scripts for projects should be in their own repositories.  Bu our conversation with @DavidBrainard and others should carry on about whether there is a role for tutorial and validation as different things. The convergence of the two functions (wrap tutorials as validation) is starting to concern me.

**Comment by npcottaris** [comment]
Agreed on the v_osTimeStep. Will simplify and speed-ify it, and make the current script into a tutorial.
I will also fix up the conflict with master today.

**Comment by wandell** [comment]
Great - I plan to work on the wiki today.  

Please merge when you are ready.  I will shift over to master and start (hopefully much smaller, shorter) branching for the next set of things.

**Comment by npcottaris** [comment]
The deed is done. NewLinear is now merged into Master. Please check. Hopefully I did not screw up.

**Pull request merged**
