### PR TITLE
Code updates to support custom oi padding

### PR DESCRIPTION
**Pull request by npcottaris**
I have updated isetbio to allow for custom padding of the oi.

1. The **default behavior** is the old one, which is 
- padding using the mean photons in the oi, and 
- a padding region equal to 1/8 of the original oi width.

2. The updated code allows for a custom padding region (specified in degrees) and a custom padding value. Valid padding values at the moment are : {'mean photons', 'zero photons'}.  'mean photons' gives the old behavior, 'zero photons'  results in padding with zeros. The code checks for the user-supplied padding value and throws an error if an invalid value is passed.

Here is a code snippet showing how you can specify custom padding.
~~~
oi = oiCreate();
% Create a padding struct specifying that the oi should be padded 
% to a total width of 1.5 deg with a padding value equal to zero photons.
padStruct = struct(...
   'sizeDegs', 1.5,...
   'value', 'zero photons');
oi =  oiSet(oi, 'pad', padStruct);
oi = oiCompute(oi, scene);
~~~

3a. If a padStruct is passed and the 'sizeDegs' field is missing, we get the default width.
3b. If a padStruct is passed and the 'value' field is missing, we get the default padding value.
3c. If the supplied 'sizeDegs' results in a padding width which is smaller than the default padding width, the default width is used instead. At the moment, no message is returned to the user regarding this choice, but we can change this.

4. All validations in isetbio and IBIOColorDetect pass.

### CODE REVIEW

**Comment by wandell** [comment]
Generally LGTM, thanks.  Can you tell me your thinking about 3c, if the specified size is smaller than the default, you use the default.

**Comment by wandell** [comment]
I guess I am also wondering if we shouldn't allow the possibility of

    oiSet(oi, 'pad value',v) and oiSet(oi, 'pad size degs', d)

**Comment by wandell** [comment]
Sometimes I do them all - a guy like me might do the value and size separately, and a guy like you would just put in the struct.  There are examples of that throughout the code, say where I attach an opticsStruct or I just set one of the values in the optics individually.

Something like this ...

case {'pad'}
        % Struct specifying the border-padding of the oi
        oi.pad = validatePadStruct(val);

case{'padvalue'}
        pad = oi.pad;
        pad.value = val;
        oi.pad = validatePadStruct(pad);

...

**Comment by npcottaris** [comment]
OK. I will implement them all. What do we want to do about 3c? I have no preference.

**Comment by wandell** [comment]
My only strong opinion is that if we don't do what they say (i.e., if they ask for 0 pad size and we give them some pad size) we should definitely tell them.


Maybe this is a choice between doing the calculation with the smaller crop and simply forcing people who want to crop to use oiCrop().  Folks around here often get rid of the padding by using oiCrop.


A value of the new format is that with the new pad parameters, we will have enough information in oiCrop to know the size and delete the border.


Brian

________________________________

**Comment by npcottaris** [comment]
Examples of current functionality (see it on GitHub to visualize the figures). 

- The default behavior (old)
default

- Setting both size and pad value using a struct
`oi = oiSet(oi, 'pad', struct('sizeDegs', 0.5, 'value', 'zero photons'));`
padstruct

- Setting pad value only, keeping default pad size
`oi = oiSet(oi, 'padvalue', 'zero photons');`
padvalue


- Setting pad size only, keeping default pad value
`oi = oiSet(oi, 'padSizeDegs',  0.5);`
padsize

 
- Setting both size (1 deg) and pad value using a struct
`oi = oiSet(oi, 'pad', struct('sizeDegs', 1.0, 'value', 'zero photons'));`
padstructlarge
-----

- Note that when padding with zero photons, the maximal illuminance is lower than when padding with mean photons, due to the convolution with the PSF. 
- Also due to the convolution with the PSF, the minimal illuminance is not zero for small padding sizes. It becomes zero, when we pad to a large size (1 deg, last example).

**Comment by npcottaris** [comment]
That's a good idea. If they ask for a smaller padSize than the default, we'll do the computations using the default pad size and give them back the cropped version. Will do that tomorrow.

**Comment by npcottaris** [comment]
@wandell: I have implemented and tested your suggestion to return an `oi` with the user-supplied `sizeDegs` when that is smaller than the default. In this case, the code uses the default padding and calls `oiCrop` to return an oi consistent with the user-supplied `sizeDegs`.

I have updated the above figures to display all this functionality. If you are fine with this implementation, let me know and I can merge this pull request, or you can do it, whatever you like. 

Again, all isetbio and IBIOColorDetect validations are passing.

**Comment by wandell** [comment]
Thanks!  Looks great.

**Pull request merged**
