### PR TITLE
Spatial resampling code.

### PR DESCRIPTION
**Pull request by wandell**
This branch includes two new routines, oiSpatialResample and sceneSpatialResample, along with a new validation script v_sceneoiSpatialResample.  These were written in response to #105 

@npcottaris - Can you please check, but also I don't know how to add 'ground truth' data for the validation script.  In fact, I probably did a poor job in writing that script so checking how I did there would also be wise.

Hope this is helpful ...

### CODE REVIEW

**Comment by npcottaris** [comment]
Hi Brian,

I checked the validation script and updated its validation (internal and external) and its plotting capabilities. Please run as standalone (to see plots) and also via ieValidateFullOne selecting 23. If all checks with you, I will go ahead and merge with master.

Thanks for adding these resampling capabilities !
Nicolas

**Comment by npcottaris** [comment]
Brian,

Should I go ahead and merge/delete the resample branch or do you still need it as a separate branch?

N.

**Comment by wandell** [comment]
Please merge.
Sorry to be slow.  Teaching.

Sent from a mobile device

On Mar 3, 2016, at 11:28 AM, Nicolas Cottaris <notifications@github.com<mailto:notifications@github.com>> wrote:


Brian,

Should I go ahead and merge/delete the resample branch or do you still need it as a separate branch?

N.

-

**Comment by npcottaris** [comment]
Resample branch merged into master and deleted from origin.

**Pull request merged**
