### PR TITLE
Emmodel

### PR DESCRIPTION
**Pull request by wandell**
I pulled out the HJ eye movement model and inserted the fixationalEM object into the coneMosaic class.  At this point coneMosaic.emGenSequence uses a simple form of fixationalEM to create the eye movements.

More work needs to be done, but given that the old model has significant problems, and that I updated the wiki page to reflect Nicolas' work, I think we should probably take this current implementation into the master.

I ran the full validations and ieRunValidationAll, and ieRunTutorialsAll.  Seems to run, but some of the data for the master validation needs to be updated because the eye movement change has a consequence for the total number of cone isomerizations in validation 13.

### CODE REVIEW

**Comment by npcottaris** [comment]
I run all the validations on my computer using the `emModel` branch and indeed everything passes except for #13 (`v_oiSequence`). 
The failure is due to a 10% difference in the number of absorptions. This is expected since the emPath is now different.
I can upload the new ground truth file and merge `emModel`  into master unless someone objects.
At Penn we have moved completely to the coneMosaicHex for all our projects, but this merge may affect others.
Let me know.

**Comment by npcottaris** [comment]
The IBIOColorDetect validations also pass with the `emBranch`. Expected as we do not use the rectMosaic.

**Comment by wandell** [comment]
Great.  Please merge and update.

We will shift towards hex too, but there are still class demos and other calculators that we use rect for.

I need to do better integration with the window code for hex.

Onward!

Brian Wandell
Stein Family Chair
Stanford University
Http://www.stanford.edu/~wandell
________________________________

**Comment by npcottaris** [comment]
New ground truth for v_oiSequence uploaded as well.

**Comment by npcottaris** [comment]
Anyone needs the remote `emModel` branch, or should I delete it?

**Comment by wandell** [comment]
Thanks, let's delete and move on.


Brian

________________________________

**Comment by npcottaris** [comment]
Done.

**Pull request merged**
